#!/bin/bash

Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'

grep model_name /proc/cpuinfo
grep NAME /etc/os-release
grep VERSION_ID /etc/os-release
uname -r
uname -m
date
hostname
echo Shell: $SHELL
echo Terminal: $TERM
echo " "
echo "████████████████"
echo " "
